# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d85ba0a2e226ca5f2a36af4cda674947013389e36715587ab7bd947850fa422f582882a50e96a74e804d09f7c12b87084c6481ceacf65c7c4b64e98b9c70eb42

test:
  secret_key_base: fe4ddaf481c615a895cb4eb14c911a677798710986af08960471d9fc3d38de4c1a9e7b4ee4275d8b025f1a1a1ba5e6be9f7caf17ff2c384628cf09cefe5ff0f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
